### ISSUE TITLE
don't display stale results in integration test dashboard, and

### ISSUE THREAD

**Issue by kdelee** [ansible/tower-dashboard#57]
Seeing results today (march 5) from feb 27 that have not failed since 2-28. The date filter is not working if I try and filter them out.

I'm not clear on expectation about for how long we want to see the old failures, but I do know even if we want to see old ones, I want it to be clear they are old and that I want to be able to filter them out.

**Comment by appuk** [comment]
The above PR should fix the issue, although the filter still does not work for date field, I added an endpoint where you can see today's results: `integration_test_results?failed_on=today`
The reason I did not invest more time in fixing the filter is because we soon want to switch to React Framework and use different elements for filters anyways
